# Generated by Django 3.2.14 on 2022-07-05 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cid', models.CharField(db_index=True, max_length=60, unique=True)),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('country_code', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'ordering': ['cid'],
            },
        ),
        migrations.CreateModel(
            name='ClientWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('lien_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
